version: '3'
services:
  stackoverflow:
    build: .
    ports:
      - "8000:5000"
    restart: always
    links:
      - mysql:dbserver
  mysql:
    image: "mysql/mysql-server:8.0"
    restart: always
